version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    volumes:
      - ./chroma_data:/chroma
    ports:
      - "8000:8000"
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    restart: unless-stopped
